### ISSUE TITLE
Release Notes Headlines

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/xlt-documentation#24]
The h3 and h4 headlines are not distinguishable enough. H3 is marked in the screenshot, all the others below are h4 and almost look the same.

![Selection_510](https://user-images.githubusercontent.com/1793856/103559245-1e0b3f00-4eb6-11eb-9feb-67c754121b03.png)

**Comment by js-xc** [comment]
1.5 vs 1.35rem. Changed h4 to 1.25 in the layout proposal branch.

**Comment by rschwietzke** [comment]
Can we do that in another branch to avoid putting too many layout changes into one branch...

**Comment by js-xc** [comment]
Sure, I'll just add it to the fixes branch I'm currently working on for Robby's comments.
